title:            MoonScript中文
description:      MoonScript中文.


host: 0.0.0.0
# the preview server used. Leave as is.
port: 8080 

# put your disqus here
disqus_shortname:
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000


#url: http://shengyang.coding.me/moonbook
url: http://www.moonscript.cn
#url: http://aronbordin.com/neo-hpstr-jekyll-theme

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: '主页'
    url: '/'
  - title: '项目'
    url: 'https://github.com/shengnoah/moonscript_for_graylog'
  - title: '标签'
    url: '/tags'
  - title: '分类'
    url: '/categories'
    type: 'categories'
  - title: '文档'
    url: '#'
    submenu:
      - title: 'MoonScript参考手册'
        url: '/documents/moonscript-reference/'
      - title: 'MoonScript API接口'
        url: '/documents/moonscript-api/'
      - title: 'MoonScript命令行'
        url: '/documents/moonscript-command-line/'
      - title: 'MoonScript标准库'
        url: '/documents/moonscript-standard-lib/'
        



# Owner/author information
owner:
  name:           糖果
  site:           https://www.candylab.net
  avatar:         images/avatar.jpg
  bio:            "MoonScript是一个神奇的语言，这是一个关于MoonScript的网站。"
  email:          49263457@email.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: shengyangcandy # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: shengnoah

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
#twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/shengnoah/moonscript_for_graylog"
  #- title: "linkedin"
  #  url: "https://br.linkedin.com/in/aronbordin"
  #- title: "youtube"
  #  url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:      true
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
locale:      en_US
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
#float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
theme: neo-hpstr-jekyll-theme
